# Generated by Django 2.2.28 on 2022-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testnewmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqweqsq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsaxax', models.BigIntegerField()),
            ],
        ),
    ]
